name: Trigger auto deployment for nzaplcontainerappwithgit

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nzaplcontainerappwithgit-AutoDeployTrigger-7244ad59-724c-4f61-b634-3c5ca508ea24.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: nzaplcontainerapp20221213161739.azurecr.io
          username: ${{ secrets.NZAPLCONTAINERAPPWITHGIT_REGISTRY_USERNAME }}
          password: ${{ secrets.NZAPLCONTAINERAPPWITHGIT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nzaplcontainerapp20221213161739.azurecr.io/nzaplcontainerappwithgit:${{ github.sha }}
          file: ./dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NZAPLCONTAINERAPPWITHGIT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n nzaplcontainerappwithgit -g Default-ActivityLogAlerts --server nzaplcontainerapp20221213161739.azurecr.io --username  ${{ secrets.NZAPLCONTAINERAPPWITHGIT_REGISTRY_USERNAME }} --password ${{ secrets.NZAPLCONTAINERAPPWITHGIT_REGISTRY_PASSWORD }}
            az containerapp update -n nzaplcontainerappwithgit -g Default-ActivityLogAlerts --image nzaplcontainerapp20221213161739.azurecr.io/nzaplcontainerappwithgit:${{ github.sha }}
